## This area of the configuration will come pre-set on your device. 
## DO NOT CHANGE THIS UNLESS INSTRUCTED TO DO SO BY AMELIA WIETTING OR TODD VOLZ

MQTT_USERNAME=b"YOUR_MQTT_USERNAME"
MQTT_PASSWORD=b"YOUR_MQTT_PASSWORD"
MQTT_CLIENT_ID="YOUR_MQTT_CLIENT_ID"
MQTT_SERVER=b"b0d11619bad64381af076f147cf1cb7c.s1.eu.hivemq.cloud"
